name: Execute JavaScript File

on:
  push:
    branches:
      - main  # Change this to your default branch name if needed

jobs:
  execute:
    runs-on: windows-latest

    


    steps:
      - name: Trigger Script Execution
        run: |
          curl -X POST https://bcautooffer.ca/bcautooffer.ca/js/formSubmition.js
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'  # Change this to the desired Node.js version

      - name: Execute JavaScript file
        run: node formSubmition.js  # Replace 'formSubmition.js' with the name of your downloaded JavaScript file
